# Generated by Django 5.1.6 on 2025-02-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=2)),
                ('sexo', models.CharField(max_length=1)),
                ('año_nacimiento', models.CharField(max_length=4)),
                ('enfermedades', models.CharField(max_length=20)),
                ('medicacion1', models.CharField(max_length=50)),
                ('dosis1', models.CharField(max_length=50)),
                ('medicacion2', models.CharField(max_length=50)),
                ('dosis2', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
