# Generated by Django 5.1.6 on 2025-03-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_mascota_delete_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
