# Generated by Django 5.1.6 on 2025-03-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_mascota_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='animal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dosis1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dosis2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='enfermedades',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='medicacion1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='medicacion2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
