# Generated by Django 5.1.6 on 2025-03-07 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_mascota_animal_alter_mascota_dosis1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_mascota', models.ImageField(blank=True, null=True, upload_to='avatares_mascota')),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.mascota')),
            ],
        ),
    ]
