# Generated by Django 5.1.6 on 2025-03-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_infoextra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoExtra',
        ),
    ]
